require('basic')
require('keybindings')
require('plugins')
require("colorscheme")
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
--exits extensions
require("plugin-config.lualine")
--exits extensions
require("plugin-config.telescope")
require("plugin-config.dashboard")
require("plugin-config.project")
require("plugin-config.nvim-treesitter")
require("lsp.setup")
require("lsp.cmp")
require("lsp.ui")
require("plugin-config.indent-blankline")
require("metals_cfg")
