require('basic')
require('plugins')
require("colorscheme")
require('keybindings')
require("plugin-config.bufferline")
require("plugin-config.nvim-treesitter")
require("plugin-config.indent-blankline")
require('plugin-config.lualine')
require('plugin-config.dashboard')
require("lsp.ui")
require("lsp.lsp-config")
require('plugin-config.dapui')
require('lsp.metals-cfg')
require('leap').add_default_mappings()
require("fidget").setup{}
--notice no color because of ts changes
